## Web Scrapping Tiket.com
**Tiket.com** adalah website resmi dari luar negeri yan menyediakan banyak sekali reservasi hotel, tiket wisata, tiket pesawat atau transportasi, dan lainnya. Namun, kali ini akan terfokus pada reservasi Hotel.

# Case Study
Adapun data yang saya gunakan nantinya untuk pengambilan scrapping, sekaligus penggunaannya di real life dan manfaat di Postgresql bagaimana:

- **Jenis data** : Nama Hotel/Vila/Apartment, Reviewnya berapa banyak, Rating dari suatu properties Hotel/Apartmenet/Villa bagaiamana, Alamatnya dimana secara spesifik, dan Harga baik itu sebelum dan sesudah diskon.
- **Penggunaan dunia nyata** :
  
  a) Data ini dapat digunakan untuk aplikasi pemesanan hotel yang memungkinkan pengguna memilih penginapan berdasarkan preferensi harga, lokasi, atau fasilitas yang tersedia. Aplikasi/website ini dapat memberikan rekomendasi kepada pengguna berdasarkan ulasan atau rating hotel. Sehingga, user dapat mempertimbangkan penginapan yang akan direservasi berdasarkan ratingnya atau kondisi harganya, atau lokasi terdekatnya.
  
  b) Untuk perusahaan -> untuk mengoptimalkan harga penginapan, berdasarkan analisis tren permintaan dan harga pesaing, atau tingkat daya tampungnya secara historis, sehingga dapat merencanakan harga yang berubah-ubah untuk waktu-waktu tertentu, seperti musim liburan atau hari kerja biasa atau event-event tertentu.
  
  c) Dapat digunakan untuk rancangan promosi tertentu berdasarkan preferensi dan kebiasaan user.

  
- **Manfaat di PostgreSQL** :

  a) Database PostgreSQL dapat digunakan untuk mengelola data hotel secara efisien, memungkinkan pencarian cepat berdasarkan filter seperti harga, rating, atau lokasi.
  
  b) Selain itu, dapat memudahkan analisis tentang tren harga atau tingkat okupansi hotel.
  
  c) PostgresQL mampu menangani data besar, terutama data penginapan ini yang pastinya cukup besar sekali datanya, karena datanya bisa update secara historis (misalkan: setiap rentang tertentu ada update harga atau penambahan penginapan baru, dan lainnya). Bahkan, juga terdapat historis penginapan yang mencakup beberapa tahun atau data dari berbagai cabang atau jaringan hotel.
  
  d) Data penginapan sangat penting untuk proses pemesanan dan pengalaman pengguna, PostgreSQL memberikan fitur keamanan yang kuat.
  
  e) Dalam hal relasional database, data penginapan bisa terhubung dengan data lainnya, seperti data pengguna, pemesanan, dan ulasan, ataupun lainnya.

  f) Dengan PostgreSQL, data penginapan dapat disimpan secara terstruktur dan dapat di-query dengan cepat.

## Library Scrapping

In [ ]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\acer\anaconda3\lib\site-packages (4.27.1)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\acer\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (2.2.3)
Requirement already satisfied: trio~=0.17 in c:\users\acer\anaconda3\lib\site-packages (from selenium) (0.28.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\acer\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\acer\anaconda3\lib\site-packages (from selenium) (2024.8.30)
Requirement already satisfied: typing_extensions~=4.9 in c:\users\acer\anaconda3\lib\site-packages (from selenium) (4.11.0)
Requirement already satisfied: websocket-client~=1.8 in c:\users\acer\anaconda3\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\acer\anaconda3\lib\site-packages (from trio~=0.17->selenium) (24.3.0)
Requirement already satisfied: sortedcontainers in c:\users\acer\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\acer\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.7)
Requirement already satisfied: outcome in c:\users\acer\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\acer\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\acer\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.17.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\acer\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\acer\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\acer\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\acer\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [ ]:
# import library yang dibutuhkan
import requests
from bs4 import BeautifulSoup
import time
from selenium import webdriver
import pandas as pd
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import os
pd.options.display.max_colwidth = 300

## Konfigurasi Scrapping

In [ ]:
url_tiket = "https://www.tiket.com/hotel/"  # Ganti URL dengan URL sebenarnya

In [ ]:
# jika running di local, maka code option dibawah ini ga perlu di running lagi, cukup 1x diatas saja
option = webdriver.ChromeOptions()
option.add_argument("--start-maximized")

tiket_hotel = webdriver.Chrome(options=option)
tiket_hotel.get(url_tiket)
# Membuat objek BeautifulSoup dari konten HTML
soup = BeautifulSoup(tiket_hotel.page_source, "html.parser")

## Scrapping Tiket
Pada **Tiket.com** akan dilakukan scrapping terkait Judul hotel reservasi, ulasan/rating, jumlah review, alamat, harga sebelum fiksasi, dan harga setelah fiksasi.

## Title/Judul Hotel Scrapping

In [ ]:
divvv_container = soup.findAll('div', attrs={'class':"ProductCard_content_container__46OfE"})
titles= []
for container in divvv_container:
    review = container.find('h2', attrs ={ 'class': "product-name_product_name__TCQ_N Text_text__PMNQZ Text_size_b2__H27gp"})
    if review:

        titles.append(review.text.strip())
# Membuat dataframe dari list judul
df_tiket_title = pd.DataFrame({'Nama Hotel/Villa': titles})
print('total properties yang didapat : ', len(df_tiket_title)) #validation data
# Menampilkan dataframe
df_tiket_title.head(500)

total properties yang didapat :  44

                                          Nama Hotel/Villa
0                         Golden Tulip Essential Tangerang
1                                        Novotel Tangerang
2                            VIVERE Hotel, ARTOTEL Curated
3                                   Episode Gading Serpong
4                               Atria Hotel Gading Serpong
5                                Padina Soho and Residence
6                             Potato Head Suites & Studios
7                    The Capital Hotel and Resort Seminyak
8                                    Svarna Suite Seminyak
9                                          Lloyds Inn Bali
10                                   Horison Seminyak Bali
11                     FuramaXclusive Ocean Beach Seminyak
12                  Ramada Encore by Wyndham Bali Seminyak
13                                  Primera Hotel Seminyak
14                                   Nikhila Seminyak Bali
15                        Hotel Indigo BALI SEMINYAK BEACH
16                   The Salila Beach Resort Seminyak Bali
17                        Seminyak Square Hotel And Villas
18             Mutiara Bali Boutique Resort Villas and Spa
19                                   Hotel Royal Singapore
20                                       Summer View Hotel
21                                  Amrise Hotel Kitchener
22                                    Oasia Hotel Downtown
23           Village Hotel Sentosa by Far East Hospitality
24                                Concorde Hotel Singapore
25                                      Dash Living Rochor
26            Village Hotel Changi by Far East Hospitality
27                       Aqueen Prestige Hotel Jalan Besar
28                                      Oasia Hotel Novena
29                                     Hotel Grand Central
30            Oasia Resort Sentosa by Far East Hospitality
31                                        Hotel JJH Aliwal
32                                   Changi Cove Singapore
33                                      M Social Singapore
34                                  The Daha Luxury Villas
35                                       Awila Villas Kuta
36                               Bobocabin Kintamani, Bali
37                                      Radea Villa Umalas
38                           Lumbini Luxury Villas and Spa
39                                Daun Bali Seminyak Hotel
40                  Ramada Encore by Wyndham Bali Seminyak
41                                 Sanur Resort Watujimbar
42                               Grand Whiz Hotel Nusa Dua
43  Aksari Luxury Resort & Spa Ubud by Ini Vie Hospitality

## Alamat Scrapping

In [ ]:
divvv_container = soup.findAll('div', attrs={'class':"ProductCard_content_container__46OfE"})
alamat= []
for container in divvv_container:
    address = container.find('span', attrs ={ 'class': "product-info_info_text__Bdfaq"})
    if address:

        alamat.append(address.text.strip())
# Membuat dataframe dari list judul
df_tiket_alamat = pd.DataFrame({'Alamat': alamat})
print('total properties yang didapat : ', len(df_tiket_alamat)) #validation data
# Menampilkan dataframe
df_tiket_alamat.head(500)

total properties yang didapat :  44

                        Alamat
0         Tangerang, Tangerang
1         Tangerang, Tangerang
2            Medang, Tangerang
3    Gading Serpong, Tangerang
4             Curug, Tangerang
5         Batuceper, Tangerang
6             Seminyak, Badung
7             Seminyak, Badung
8             Seminyak, Badung
9             Seminyak, Badung
10                Kuta, Badung
11            Seminyak, Badung
12            Seminyak, Badung
13            Seminyak, Badung
14            Seminyak, Badung
15            Seminyak, Badung
16            Seminyak, Badung
17            Seminyak, Badung
18            Seminyak, Badung
19           Novena, Singapore
20           Rochor, Singapore
21          Kallang, Singapore
22           Outram, Singapore
23   Sentosa Island, Singapore
24          Orchard, Singapore
25           Rochor, Singapore
26           Changi, Singapore
27          Kallang, Singapore
28           Novena, Singapore
29          Orchard, Singapore
30   Sentosa Island, Singapore
31           Rochor, Singapore
32           Changi, Singapore
33  Singapore River, Singapore
34                       Villa
35                       Villa
36                       Cabin
37                       Villa
38                       Villa
39            Seminyak, Badung
40            Seminyak, Badung
41             Sanur, Denpasar
42            Nusa Dua, Badung
43        Tegallalang, Gianyar

## Rating Scrapping

In [ ]:
divvv_container = soup.findAll('div', attrs={'class':"ProductCard_content_container__46OfE"})
rating= []
for container in divvv_container:
    ratings = container.find('span', attrs ={ 'class': ""})
    if ratings:

        rating.append(ratings.text.strip())
# Membuat dataframe dari list judul
df_tiket_rating = pd.DataFrame({'Rating': rating})
print('total properties yang didapat : ', len(df_tiket_rating)) #validation data
# Menampilkan dataframe
df_tiket_rating.head(500)

total properties yang didapat :  44

   Rating
0   4,3/5
1   4,5/5
2   4,7/5
3   4,7/5
4   4,4/5
5   4,5/5
6   4,8/5
7   4,3/5
8   4,3/5
9   4,4/5
10  4,4/5
11  4,1/5
12  4,5/5
13  4,2/5
14  4,3/5
15  4,7/5
16  4,7/5
17  4,3/5
18  4,4/5
19  4,2/5
20  4,3/5
21    4/5
22  4,7/5
23  4,4/5
24  4,4/5
25    4/5
26    4/5
27  4,6/5
28  4,7/5
29  4,3/5
30  4,8/5
31  3,8/5
32  4,3/5
33    4/5
34  4,7/5
35  4,2/5
36  4,3/5
37  4,3/5
38  4,4/5
39  4,5/5
40  4,5/5
41  4,9/5
42  4,5/5
43  4,6/5

## Jumlah Review Scrapping

In [ ]:
divvv_container = soup.findAll('div', attrs={'class':"ProductCard_content_container__46OfE"})
review = []
for container in divvv_container:
    reviews = container.find('span', attrs ={ 'class': "product-info_review_count__im6ZN Text_text__PMNQZ"})
    if reviews:

        review.append(reviews.text.strip())
# Membuat dataframe dari list judul
df_tiket_review = pd.DataFrame({'Jumlah Review': review})
print('total properties yang didapat : ', len(df_tiket_review)) #validation data
# Menampilkan dataframe
df_tiket_review.head(500)

total properties yang didapat :  44

   Jumlah Review
0   1.5rb Review
1     681 Review
2     464 Review
3   1.7rb Review
4   1.6rb Review
5     318 Review
6     498 Review
7     727 Review
8      40 Review
9     828 Review
10  1.2rb Review
11    687 Review
12  2.2rb Review
13  3.2rb Review
14  2.1rb Review
15    477 Review
16     93 Review
17    144 Review
18    150 Review
19    582 Review
20    235 Review
21     58 Review
22     38 Review
23    138 Review
24    422 Review
25     47 Review
26    152 Review
27     71 Review
28    128 Review
29  1.1rb Review
30      6 Review
31    281 Review
32    184 Review
33    154 Review
34     58 Review
35     96 Review
36    528 Review
37    294 Review
38    170 Review
39  1.5rb Review
40  2.2rb Review
41    268 Review
42    836 Review
43    638 Review

## Harga Sebelum Fiksasi Scrapping

In [ ]:
divvv_container = soup.findAll('div', attrs={'class':"ProductCard_content_container__46OfE"})
harga_asli = []
for container in divvv_container:
    harggaa = container.find('div', attrs ={ 'class': "Text_text__PMNQZ Text_variant_lowEmphasis__SpdCR Text_size_b3__xDIF_ Text_align_left__IbT8t"})
    if harggaa:

        harga_asli.append(harggaa.text.strip())
# Membuat dataframe dari list judul
df_tiket_harga_asli = pd.DataFrame({'Harga Asli Sebelum Diskon': harga_asli})
print('total properties yang didapat : ', len(df_tiket_harga_asli)) #validation data
# Menampilkan dataframe
df_tiket_harga_asli.head(500)

total properties yang didapat :  44

   Harga Asli Sebelum Diskon
0
1
2
3              IDR 1.137.272
4
5                IDR 699.637
6              IDR 4.535.536
7
8
9              IDR 1.637.405
10
11
12             IDR 1.427.726
13               IDR 273.222
14
15
16             IDR 2.950.413
17
18             IDR 2.024.256
19
20             IDR 1.907.228
21
22             IDR 3.557.062
23             IDR 3.347.816
24             IDR 3.567.320
25             IDR 1.983.856
26             IDR 1.935.345
27
28
29
30             IDR 3.034.068
31
32
33             IDR 1.930.879
34             IDR 7.204.364
35             IDR 1.877.685
36               IDR 981.598
37             IDR 2.231.404
38             IDR 5.312.245
39
40
41
42               IDR 816.243
43

# Fix Harga Scrapping

In [ ]:
divvv_container = soup.findAll('div', attrs={'class':"ProductCard_content_container__46OfE"})
harga = []
for container in divvv_container:
    hargga = container.find('div', attrs ={ 'class': "Text_text__PMNQZ Text_variant_price__sQ_5O Text_size_b2__H27gp Text_align_left__IbT8t Text_weight_bold__ukOCJ"})
    if hargga:

        harga.append(hargga.text.strip())
# Membuat dataframe dari list judul
df_tiket_harga = pd.DataFrame({'Harga Fiksasi Setelah ada Diskon/Tidak': harga})
print('total properties yang didapat : ', len(df_tiket_harga)) #validation data
# Menampilkan dataframe
df_tiket_harga.head(500)

total properties yang didapat :  44

   Harga Fiksasi Setelah ada Diskon/Tidak
0                             IDR 379.202
1                             IDR 904.959
2                             IDR 789.302
3                           IDR 1.136.446
4                             IDR 774.518
5                             IDR 360.312
6                           IDR 4.041.163
7                             IDR 709.091
8                             IDR 388.435
9                             IDR 925.076
10                            IDR 541.478
11                            IDR 952.217
12                            IDR 821.255
13                            IDR 267.758
14                            IDR 349.122
15                          IDR 3.429.540
16                            IDR 824.794
17                            IDR 597.763
18                            IDR 901.879
19                          IDR 1.379.393
20                          IDR 1.495.464
21                          IDR 1.196.068
22                          IDR 2.774.806
23                          IDR 2.611.582
24                          IDR 2.100.190
25                          IDR 1.091.559
26                          IDR 1.622.483
27                          IDR 1.513.664
28                          IDR 2.133.089
29                          IDR 1.525.802
30                          IDR 2.543.492
31                            IDR 711.121
32                          IDR 1.481.452
33                          IDR 1.834.336
34                          IDR 2.808.000
35                          IDR 1.600.000
36                            IDR 972.674
37                            IDR 725.371
38                          IDR 2.275.854
39                            IDR 499.227
40                            IDR 476.405
41                            IDR 883.795
42                            IDR 588.283
43                          IDR 2.561.275

# Transformasi Data After Scrapping

## Penggabungan Dataframe Scrapping Tiket.com

In [ ]:
df_tiketcom = pd.concat([df_tiket_title, df_tiket_alamat, df_tiket_rating, df_tiket_review, df_tiket_harga_asli, df_tiket_harga], axis=1)
print('total properties yang didapat : ', len(df_tiketcom))
df_tiketcom.head(100)

total properties yang didapat :  44

,Nama Hotel/Villa,Alamat,Rating,Jumlah Review,Harga Asli Sebelum Diskon,Harga Fiksasi Setelah ada Diskon/Tidak
0,Golden Tulip Essential Tangerang,"Tangerang, Tangerang","4,3/5",1.5rb Review,,IDR 379.202
1,Novotel Tangerang,"Tangerang, Tangerang","4,5/5",681 Review,,IDR 904.959
2,"VIVERE Hotel, ARTOTEL Curated","Medang, Tangerang","4,7/5",464 Review,,IDR 789.302
3,Episode Gading Serpong,"Gading Serpong, Tangerang","4,7/5",1.7rb Review,IDR 1.137.272,IDR 1.136.446
4,Atria Hotel Gading Serpong,"Curug, Tangerang","4,4/5",1.6rb Review,,IDR 774.518
5,Padina Soho and Residence,"Batuceper, Tangerang","4,5/5",318 Review,IDR 699.637,IDR 360.312
6,Potato Head Suites & Studios,"Seminyak, Badung","4,8/5",498 Review,IDR 4.535.536,IDR 4.041.163
7,The Capital Hotel and Resort Seminyak,"Seminyak, Badung","4,3/5",727 Review,,IDR 709.091
8,Svarna Suite Seminyak,"Seminyak, Badung","4,3/5",40 Review,,IDR 388.435
9,Lloyds Inn Bali,"Seminyak, Badung","4,4/5",828 Review,IDR 1.637.405,IDR 925.076
10,Horison Seminyak Bali,"Kuta, Badung","4,4/5",1.2rb Review,,IDR 541.478
11,FuramaXclusive Ocean Beach Seminyak,"Seminyak, Badung","4,1/5",687 Review,,IDR 952.217
12,Ramada Encore by Wyndham Bali Seminyak,"Seminyak, Badung","4,5/5",2.2rb Review,IDR 1.427.726,IDR 821.255
13,Primera Hotel Seminyak,"Seminyak, Badung","4,2/5",3.2rb Review,IDR 273.222,IDR 267.758
14,Nikhila Seminyak Bali,"Seminyak, Badung","4,3/5",2.1rb Review,,IDR 349.122
15,Hotel Indigo BALI SEMINYAK BEACH,"Seminyak, Badung","4,7/5",477 Review,,IDR 3.429.540
16,The Salila Beach Resort Seminyak Bali,"Seminyak, Badung","4,7/5",93 Review,IDR 2.950.413,IDR 824.794
17,Seminyak Square Hotel And Villas,"Seminyak, Badung","4,3/5",144 Review,,IDR 597.763
18,Mutiara Bali Boutique Resort Villas and Spa,"Seminyak, Badung","4,4/5",150 Review,IDR 2.024.256,IDR 901.879
19,Hotel Royal Singapore,"Novena, Singapore","4,2/5",582 Review,,IDR 1.379.393
20,Summer View Hotel,"Rochor, Singapore","4,3/5",235 Review,IDR 1.907.228,IDR 1.495.464
21,Amrise Hotel Kitchener,"Kallang, Singapore",4/5,58 Review,,IDR 1.196.068
22,Oasia Hotel Downtown,"Outram, Singapore","4,7/5",38 Review,IDR 3.557.062,IDR 2.774.806
23,Village Hotel Sentosa by Far East Hospitality,"Sentosa Island, Singapore","4,4/5",138 Review,IDR 3.347.816,IDR 2.611.582
24,Concorde Hotel Singapore,"Orchard, Singapore","4,4/5",422 Review,IDR 3.567.320,IDR 2.100.190
25,Dash Living Rochor,"Rochor, Singapore",4/5,47 Review,IDR 1.983.856,IDR 1.091.559
26,Village Hotel Changi by Far East Hospitality,"Changi, Singapore",4/5,152 Review,IDR 1.935.345,IDR 1.622.483
27,Aqueen Prestige Hotel Jalan Besar,"Kallang, Singapore","4,6/5",71 Review,,IDR 1.513.664
28,Oasia Hotel Novena,"Novena, Singapore","4,7/5",128 Review,,IDR 2.133.089
29,Hotel Grand Central,"Orchard, Singapore","4,3/5",1.1rb Review,,IDR 1.525.802
30,Oasia Resort Sentosa by Far East Hospitality,"Sentosa Island, Singapore","4,8/5",6 Review,IDR 3.034.068,IDR 2.543.492
31,Hotel JJH Aliwal,"Rochor, Singapore","3,8/5",281 Review,,IDR 711.121
32,Changi Cove Singapore,"Changi, Singapore","4,3/5",184 Review,,IDR 1.481.452
33,M Social Singapore,"Singapore River, Singapore",4/5,154 Review,IDR 1.930.879,IDR 1.834.336
34,The Daha Luxury Villas,Villa,"4,7/5",58 Review,IDR 7.204.364,IDR 2.808.000
35,Awila Villas Kuta,Villa,"4,2/5",96 Review,IDR 1.877.685,IDR 1.600.000
36,"Bobocabin Kintamani, Bali",Cabin,"4,3/5",528 Review,IDR 981.598,IDR 972.674
37,Radea Villa Umalas,Villa,"4,3/5",294 Review,IDR 2.231.404,IDR 725.371
38,Lumbini Luxury Villas and Spa,Villa,"4,4/5",170 Review,IDR 5.312.245,IDR 2.275.854
39,Daun Bali Seminyak Hotel,"Seminyak, Badung","4,5/5",1.5rb Review,,IDR 499.227
40,Ramada Encore by Wyndham Bali Seminyak,"Seminyak, Badung","4,5/5",2.2rb Review,,IDR 476.405
41,Sanur Resort Watujimbar,"Sanur, Denpasar","4,9/5",268 Review,,IDR 883.795
42,Grand Whiz Hotel Nusa Dua,"Nusa Dua, Badung","4,5/5",836 Review,IDR 816.243,IDR 588.283
43,Aksari Luxury Resort & Spa Ubud by Ini Vie Hospitality,"Tegallalang, Gianyar","4,6/5",638 Review,,IDR 2.561.275

In [ ]:
df_tiketcom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 6 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Nama Hotel/Villa                        44 non-null     object
 1   Alamat                                  44 non-null     object
 2   Rating                                  44 non-null     object
 3   Jumlah Review                           44 non-null     object
 4   Harga Asli Sebelum Diskon               44 non-null     object
 5   Harga Fiksasi Setelah ada Diskon/Tidak  44 non-null     object
dtypes: object(6)
memory usage: 2.2+ KB

## Pembersihan Data Teks

In [ ]:
import re

### 1. Menambahkan Kata ', Bali' Pada Alamat yang terdapat Kata 'Villa dan Cabin'

In [ ]:
df_tiketcom['Alamat'] = df_tiketcom['Alamat'].apply(lambda x: re.sub(r'\b(Villa|Cabin)\b', 'Bali', x))
df_tiketcom

,Nama Hotel/Villa,Alamat,Rating,Jumlah Review,Harga Asli Sebelum Diskon,Harga Fiksasi Setelah ada Diskon/Tidak
0,Golden Tulip Essential Tangerang,"Tangerang, Tangerang","4,3/5",1.5rb Review,,IDR 379.202
1,Novotel Tangerang,"Tangerang, Tangerang","4,5/5",681 Review,,IDR 904.959
2,"VIVERE Hotel, ARTOTEL Curated","Medang, Tangerang","4,7/5",464 Review,,IDR 789.302
3,Episode Gading Serpong,"Gading Serpong, Tangerang","4,7/5",1.7rb Review,IDR 1.137.272,IDR 1.136.446
4,Atria Hotel Gading Serpong,"Curug, Tangerang","4,4/5",1.6rb Review,,IDR 774.518
5,Padina Soho and Residence,"Batuceper, Tangerang","4,5/5",318 Review,IDR 699.637,IDR 360.312
6,Potato Head Suites & Studios,"Seminyak, Badung","4,8/5",498 Review,IDR 4.535.536,IDR 4.041.163
7,The Capital Hotel and Resort Seminyak,"Seminyak, Badung","4,3/5",727 Review,,IDR 709.091
8,Svarna Suite Seminyak,"Seminyak, Badung","4,3/5",40 Review,,IDR 388.435
9,Lloyds Inn Bali,"Seminyak, Badung","4,4/5",828 Review,IDR 1.637.405,IDR 925.076
10,Horison Seminyak Bali,"Kuta, Badung","4,4/5",1.2rb Review,,IDR 541.478
11,FuramaXclusive Ocean Beach Seminyak,"Seminyak, Badung","4,1/5",687 Review,,IDR 952.217
12,Ramada Encore by Wyndham Bali Seminyak,"Seminyak, Badung","4,5/5",2.2rb Review,IDR 1.427.726,IDR 821.255
13,Primera Hotel Seminyak,"Seminyak, Badung","4,2/5",3.2rb Review,IDR 273.222,IDR 267.758
14,Nikhila Seminyak Bali,"Seminyak, Badung","4,3/5",2.1rb Review,,IDR 349.122
15,Hotel Indigo BALI SEMINYAK BEACH,"Seminyak, Badung","4,7/5",477 Review,,IDR 3.429.540
16,The Salila Beach Resort Seminyak Bali,"Seminyak, Badung","4,7/5",93 Review,IDR 2.950.413,IDR 824.794
17,Seminyak Square Hotel And Villas,"Seminyak, Badung","4,3/5",144 Review,,IDR 597.763
18,Mutiara Bali Boutique Resort Villas and Spa,"Seminyak, Badung","4,4/5",150 Review,IDR 2.024.256,IDR 901.879
19,Hotel Royal Singapore,"Novena, Singapore","4,2/5",582 Review,,IDR 1.379.393
20,Summer View Hotel,"Rochor, Singapore","4,3/5",235 Review,IDR 1.907.228,IDR 1.495.464
21,Amrise Hotel Kitchener,"Kallang, Singapore",4/5,58 Review,,IDR 1.196.068
22,Oasia Hotel Downtown,"Outram, Singapore","4,7/5",38 Review,IDR 3.557.062,IDR 2.774.806
23,Village Hotel Sentosa by Far East Hospitality,"Sentosa Island, Singapore","4,4/5",138 Review,IDR 3.347.816,IDR 2.611.582
24,Concorde Hotel Singapore,"Orchard, Singapore","4,4/5",422 Review,IDR 3.567.320,IDR 2.100.190
25,Dash Living Rochor,"Rochor, Singapore",4/5,47 Review,IDR 1.983.856,IDR 1.091.559
26,Village Hotel Changi by Far East Hospitality,"Changi, Singapore",4/5,152 Review,IDR 1.935.345,IDR 1.622.483
27,Aqueen Prestige Hotel Jalan Besar,"Kallang, Singapore","4,6/5",71 Review,,IDR 1.513.664
28,Oasia Hotel Novena,"Novena, Singapore","4,7/5",128 Review,,IDR 2.133.089
29,Hotel Grand Central,"Orchard, Singapore","4,3/5",1.1rb Review,,IDR 1.525.802
30,Oasia Resort Sentosa by Far East Hospitality,"Sentosa Island, Singapore","4,8/5",6 Review,IDR 3.034.068,IDR 2.543.492
31,Hotel JJH Aliwal,"Rochor, Singapore","3,8/5",281 Review,,IDR 711.121
32,Changi Cove Singapore,"Changi, Singapore","4,3/5",184 Review,,IDR 1.481.452
33,M Social Singapore,"Singapore River, Singapore",4/5,154 Review,IDR 1.930.879,IDR 1.834.336
34,The Daha Luxury Villas,Bali,"4,7/5",58 Review,IDR 7.204.364,IDR 2.808.000
35,Awila Villas Kuta,Bali,"4,2/5",96 Review,IDR 1.877.685,IDR 1.600.000
36,"Bobocabin Kintamani, Bali",Bali,"4,3/5",528 Review,IDR 981.598,IDR 972.674
37,Radea Villa Umalas,Bali,"4,3/5",294 Review,IDR 2.231.404,IDR 725.371
38,Lumbini Luxury Villas and Spa,Bali,"4,4/5",170 Review,IDR 5.312.245,IDR 2.275.854
39,Daun Bali Seminyak Hotel,"Seminyak, Badung","4,5/5",1.5rb Review,,IDR 499.227
40,Ramada Encore by Wyndham Bali Seminyak,"Seminyak, Badung","4,5/5",2.2rb Review,,IDR 476.405
41,Sanur Resort Watujimbar,"Sanur, Denpasar","4,9/5",268 Review,,IDR 883.795
42,Grand Whiz Hotel Nusa Dua,"Nusa Dua, Badung","4,5/5",836 Review,IDR 816.243,IDR 588.283
43,Aksari Luxury Resort & Spa Ubud by Ini Vie Hospitality,"Tegallalang, Gianyar","4,6/5",638 Review,,IDR 2.561.275

Pada data tersebut awalnya data baris ke 28 hingga 32 hanya bertuliskan Villa atau Cabin tidak ada spesifik merujuk pada
daerah tertentu, maka ketika saya cek penginapan-penginapan tersebut berada di Bali, maka saya melakukan fungsi `re.sub(r'\b(Villa|Cabin)\b', 'Bali', x)` untuk mengganti kata Cabin atau Villa menjadi **Bali**.

### 2. a) Memilih pada rating yaitu angka ratingnya saja

In [ ]:
df_tiketcom['Angka Rating'] = df_tiketcom['Rating'].str.extract(r'^([\d,]+)')[0]
df_tiketcom['Angka Rating'] = df_tiketcom['Angka Rating'].str.replace(',', '.').astype(float)
df_tiketcom.head(100)

,Nama Hotel/Villa,Alamat,Rating,Jumlah Review,Harga Asli Sebelum Diskon,Harga Fiksasi Setelah ada Diskon/Tidak,Angka Rating
0,Golden Tulip Essential Tangerang,"Tangerang, Tangerang","4,3/5",1.5rb Review,,IDR 379.202,4.3
1,Novotel Tangerang,"Tangerang, Tangerang","4,5/5",681 Review,,IDR 904.959,4.5
2,"VIVERE Hotel, ARTOTEL Curated","Medang, Tangerang","4,7/5",464 Review,,IDR 789.302,4.7
3,Episode Gading Serpong,"Gading Serpong, Tangerang","4,7/5",1.7rb Review,IDR 1.137.272,IDR 1.136.446,4.7
4,Atria Hotel Gading Serpong,"Curug, Tangerang","4,4/5",1.6rb Review,,IDR 774.518,4.4
5,Padina Soho and Residence,"Batuceper, Tangerang","4,5/5",318 Review,IDR 699.637,IDR 360.312,4.5
6,Potato Head Suites & Studios,"Seminyak, Badung","4,8/5",498 Review,IDR 4.535.536,IDR 4.041.163,4.8
7,The Capital Hotel and Resort Seminyak,"Seminyak, Badung","4,3/5",727 Review,,IDR 709.091,4.3
8,Svarna Suite Seminyak,"Seminyak, Badung","4,3/5",40 Review,,IDR 388.435,4.3
9,Lloyds Inn Bali,"Seminyak, Badung","4,4/5",828 Review,IDR 1.637.405,IDR 925.076,4.4
10,Horison Seminyak Bali,"Kuta, Badung","4,4/5",1.2rb Review,,IDR 541.478,4.4
11,FuramaXclusive Ocean Beach Seminyak,"Seminyak, Badung","4,1/5",687 Review,,IDR 952.217,4.1
12,Ramada Encore by Wyndham Bali Seminyak,"Seminyak, Badung","4,5/5",2.2rb Review,IDR 1.427.726,IDR 821.255,4.5
13,Primera Hotel Seminyak,"Seminyak, Badung","4,2/5",3.2rb Review,IDR 273.222,IDR 267.758,4.2
14,Nikhila Seminyak Bali,"Seminyak, Badung","4,3/5",2.1rb Review,,IDR 349.122,4.3
15,Hotel Indigo BALI SEMINYAK BEACH,"Seminyak, Badung","4,7/5",477 Review,,IDR 3.429.540,4.7
16,The Salila Beach Resort Seminyak Bali,"Seminyak, Badung","4,7/5",93 Review,IDR 2.950.413,IDR 824.794,4.7
17,Seminyak Square Hotel And Villas,"Seminyak, Badung","4,3/5",144 Review,,IDR 597.763,4.3
18,Mutiara Bali Boutique Resort Villas and Spa,"Seminyak, Badung","4,4/5",150 Review,IDR 2.024.256,IDR 901.879,4.4
19,Hotel Royal Singapore,"Novena, Singapore","4,2/5",582 Review,,IDR 1.379.393,4.2
20,Summer View Hotel,"Rochor, Singapore","4,3/5",235 Review,IDR 1.907.228,IDR 1.495.464,4.3
21,Amrise Hotel Kitchener,"Kallang, Singapore",4/5,58 Review,,IDR 1.196.068,4.0
22,Oasia Hotel Downtown,"Outram, Singapore","4,7/5",38 Review,IDR 3.557.062,IDR 2.774.806,4.7
23,Village Hotel Sentosa by Far East Hospitality,"Sentosa Island, Singapore","4,4/5",138 Review,IDR 3.347.816,IDR 2.611.582,4.4
24,Concorde Hotel Singapore,"Orchard, Singapore","4,4/5",422 Review,IDR 3.567.320,IDR 2.100.190,4.4
25,Dash Living Rochor,"Rochor, Singapore",4/5,47 Review,IDR 1.983.856,IDR 1.091.559,4.0
26,Village Hotel Changi by Far East Hospitality,"Changi, Singapore",4/5,152 Review,IDR 1.935.345,IDR 1.622.483,4.0
27,Aqueen Prestige Hotel Jalan Besar,"Kallang, Singapore","4,6/5",71 Review,,IDR 1.513.664,4.6
28,Oasia Hotel Novena,"Novena, Singapore","4,7/5",128 Review,,IDR 2.133.089,4.7
29,Hotel Grand Central,"Orchard, Singapore","4,3/5",1.1rb Review,,IDR 1.525.802,4.3
30,Oasia Resort Sentosa by Far East Hospitality,"Sentosa Island, Singapore","4,8/5",6 Review,IDR 3.034.068,IDR 2.543.492,4.8
31,Hotel JJH Aliwal,"Rochor, Singapore","3,8/5",281 Review,,IDR 711.121,3.8
32,Changi Cove Singapore,"Changi, Singapore","4,3/5",184 Review,,IDR 1.481.452,4.3
33,M Social Singapore,"Singapore River, Singapore",4/5,154 Review,IDR 1.930.879,IDR 1.834.336,4.0
34,The Daha Luxury Villas,Bali,"4,7/5",58 Review,IDR 7.204.364,IDR 2.808.000,4.7
35,Awila Villas Kuta,Bali,"4,2/5",96 Review,IDR 1.877.685,IDR 1.600.000,4.2
36,"Bobocabin Kintamani, Bali",Bali,"4,3/5",528 Review,IDR 981.598,IDR 972.674,4.3
37,Radea Villa Umalas,Bali,"4,3/5",294 Review,IDR 2.231.404,IDR 725.371,4.3
38,Lumbini Luxury Villas and Spa,Bali,"4,4/5",170 Review,IDR 5.312.245,IDR 2.275.854,4.4
39,Daun Bali Seminyak Hotel,"Seminyak, Badung","4,5/5",1.5rb Review,,IDR 499.227,4.5
40,Ramada Encore by Wyndham Bali Seminyak,"Seminyak, Badung","4,5/5",2.2rb Review,,IDR 476.405,4.5
41,Sanur Resort Watujimbar,"Sanur, Denpasar","4,9/5",268 Review,,IDR 883.795,4.9
42,Grand Whiz Hotel Nusa Dua,"Nusa Dua, Badung","4,5/5",836 Review,IDR 816.243,IDR 588.283,4.5
43,Aksari Luxury Resort & Spa Ubud by Ini Vie Hospitality,"Tegallalang, Gianyar","4,6/5",638 Review,,IDR 2.561.275,4.6

In [ ]:
df_tiketcom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 7 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Nama Hotel/Villa                        44 non-null     object
 1   Alamat                                  44 non-null     object
 2   Rating                                  44 non-null     object
 3   Jumlah Review                           44 non-null     object
 4   Harga Asli Sebelum Diskon               44 non-null     object
 5   Harga Fiksasi Setelah ada Diskon/Tidak  44 non-null     object
 6   Angka Rating                            44 non-null     float64
dtypes: float64(1), object(6)
memory usage: 2.5+ KB

Pada kolom **'Rating'** masih bentuknya object atau string dan ingin mengextract dengan mengambil angka ratingnya saja, seperti 4,5/5 -> yang diambil adalah 4,5 (bentuk tipenya float). sehingga dengan menggunakan:
- Fungsi `str.extract(r'^([\d,]+)')[0]` akan mengambil angka sebelum tanda '/'.
- Fungsi `str.replace(',', '.').astype(float)` akan mengubah tipe data menjadi numerik.

Sehingga, pada kolom **'Angka Rating'** muncul output dari angka ratingnya saja.

### 2. b) Pada kolom review akan diextract ke numeriknya saja

In [ ]:
def extract_review(review):
    import re
    match = re.match(r'([\d.]+)(rb)?', review) #untuk menangkap kata yang ada 'rb'
    if match:
        number = float(match.group(1))          # untuk angka float
        if match.group(2) == 'rb':             # Jika ada 'rb', kalikan 1000
            number *= 1000
        return number
    return None  # Jika tidak cocok, kembalikan None

# Terapkan fungsi ke kolom 'Review'
df_tiketcom['Total Review Fix'] = df_tiketcom['Jumlah Review'].apply(extract_review)
df_tiketcom.head(100)

,Nama Hotel/Villa,Alamat,Rating,Jumlah Review,Harga Asli Sebelum Diskon,Harga Fiksasi Setelah ada Diskon/Tidak,Angka Rating,Total Review Fix
0,Golden Tulip Essential Tangerang,"Tangerang, Tangerang","4,3/5",1.5rb Review,,IDR 379.202,4.3,1500.0
1,Novotel Tangerang,"Tangerang, Tangerang","4,5/5",681 Review,,IDR 904.959,4.5,681.0
2,"VIVERE Hotel, ARTOTEL Curated","Medang, Tangerang","4,7/5",464 Review,,IDR 789.302,4.7,464.0
3,Episode Gading Serpong,"Gading Serpong, Tangerang","4,7/5",1.7rb Review,IDR 1.137.272,IDR 1.136.446,4.7,1700.0
4,Atria Hotel Gading Serpong,"Curug, Tangerang","4,4/5",1.6rb Review,,IDR 774.518,4.4,1600.0
5,Padina Soho and Residence,"Batuceper, Tangerang","4,5/5",318 Review,IDR 699.637,IDR 360.312,4.5,318.0
6,Potato Head Suites & Studios,"Seminyak, Badung","4,8/5",498 Review,IDR 4.535.536,IDR 4.041.163,4.8,498.0
7,The Capital Hotel and Resort Seminyak,"Seminyak, Badung","4,3/5",727 Review,,IDR 709.091,4.3,727.0
8,Svarna Suite Seminyak,"Seminyak, Badung","4,3/5",40 Review,,IDR 388.435,4.3,40.0
9,Lloyds Inn Bali,"Seminyak, Badung","4,4/5",828 Review,IDR 1.637.405,IDR 925.076,4.4,828.0
10,Horison Seminyak Bali,"Kuta, Badung","4,4/5",1.2rb Review,,IDR 541.478,4.4,1200.0
11,FuramaXclusive Ocean Beach Seminyak,"Seminyak, Badung","4,1/5",687 Review,,IDR 952.217,4.1,687.0
12,Ramada Encore by Wyndham Bali Seminyak,"Seminyak, Badung","4,5/5",2.2rb Review,IDR 1.427.726,IDR 821.255,4.5,2200.0
13,Primera Hotel Seminyak,"Seminyak, Badung","4,2/5",3.2rb Review,IDR 273.222,IDR 267.758,4.2,3200.0
14,Nikhila Seminyak Bali,"Seminyak, Badung","4,3/5",2.1rb Review,,IDR 349.122,4.3,2100.0
15,Hotel Indigo BALI SEMINYAK BEACH,"Seminyak, Badung","4,7/5",477 Review,,IDR 3.429.540,4.7,477.0
16,The Salila Beach Resort Seminyak Bali,"Seminyak, Badung","4,7/5",93 Review,IDR 2.950.413,IDR 824.794,4.7,93.0
17,Seminyak Square Hotel And Villas,"Seminyak, Badung","4,3/5",144 Review,,IDR 597.763,4.3,144.0
18,Mutiara Bali Boutique Resort Villas and Spa,"Seminyak, Badung","4,4/5",150 Review,IDR 2.024.256,IDR 901.879,4.4,150.0
19,Hotel Royal Singapore,"Novena, Singapore","4,2/5",582 Review,,IDR 1.379.393,4.2,582.0
20,Summer View Hotel,"Rochor, Singapore","4,3/5",235 Review,IDR 1.907.228,IDR 1.495.464,4.3,235.0
21,Amrise Hotel Kitchener,"Kallang, Singapore",4/5,58 Review,,IDR 1.196.068,4.0,58.0
22,Oasia Hotel Downtown,"Outram, Singapore","4,7/5",38 Review,IDR 3.557.062,IDR 2.774.806,4.7,38.0
23,Village Hotel Sentosa by Far East Hospitality,"Sentosa Island, Singapore","4,4/5",138 Review,IDR 3.347.816,IDR 2.611.582,4.4,138.0
24,Concorde Hotel Singapore,"Orchard, Singapore","4,4/5",422 Review,IDR 3.567.320,IDR 2.100.190,4.4,422.0
25,Dash Living Rochor,"Rochor, Singapore",4/5,47 Review,IDR 1.983.856,IDR 1.091.559,4.0,47.0
26,Village Hotel Changi by Far East Hospitality,"Changi, Singapore",4/5,152 Review,IDR 1.935.345,IDR 1.622.483,4.0,152.0
27,Aqueen Prestige Hotel Jalan Besar,"Kallang, Singapore","4,6/5",71 Review,,IDR 1.513.664,4.6,71.0
28,Oasia Hotel Novena,"Novena, Singapore","4,7/5",128 Review,,IDR 2.133.089,4.7,128.0
29,Hotel Grand Central,"Orchard, Singapore","4,3/5",1.1rb Review,,IDR 1.525.802,4.3,1100.0
30,Oasia Resort Sentosa by Far East Hospitality,"Sentosa Island, Singapore","4,8/5",6 Review,IDR 3.034.068,IDR 2.543.492,4.8,6.0
31,Hotel JJH Aliwal,"Rochor, Singapore","3,8/5",281 Review,,IDR 711.121,3.8,281.0
32,Changi Cove Singapore,"Changi, Singapore","4,3/5",184 Review,,IDR 1.481.452,4.3,184.0
33,M Social Singapore,"Singapore River, Singapore",4/5,154 Review,IDR 1.930.879,IDR 1.834.336,4.0,154.0
34,The Daha Luxury Villas,Bali,"4,7/5",58 Review,IDR 7.204.364,IDR 2.808.000,4.7,58.0
35,Awila Villas Kuta,Bali,"4,2/5",96 Review,IDR 1.877.685,IDR 1.600.000,4.2,96.0
36,"Bobocabin Kintamani, Bali",Bali,"4,3/5",528 Review,IDR 981.598,IDR 972.674,4.3,528.0
37,Radea Villa Umalas,Bali,"4,3/5",294 Review,IDR 2.231.404,IDR 725.371,4.3,294.0
38,Lumbini Luxury Villas and Spa,Bali,"4,4/5",170 Review,IDR 5.312.245,IDR 2.275.854,4.4,170.0
39,Daun Bali Seminyak Hotel,"Seminyak, Badung","4,5/5",1.5rb Review,,IDR 499.227,4.5,1500.0
40,Ramada Encore by Wyndham Bali Seminyak,"Seminyak, Badung","4,5/5",2.2rb Review,,IDR 476.405,4.5,2200.0
41,Sanur Resort Watujimbar,"Sanur, Denpasar","4,9/5",268 Review,,IDR 883.795,4.9,268.0
42,Grand Whiz Hotel Nusa Dua,"Nusa Dua, Badung","4,5/5",836 Review,IDR 816.243,IDR 588.283,4.5,836.0
43,Aksari Luxury Resort & Spa Ubud by Ini Vie Hospitality,"Tegallalang, Gianyar","4,6/5",638 Review,,IDR 2.561.275,4.6,638.0

In [ ]:
df_tiketcom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Nama Hotel/Villa                        38 non-null     object
 1   Alamat                                  38 non-null     object
 2   Rating                                  38 non-null     object
 3   Jumlah Review                           38 non-null     object
 4   Harga Asli Sebelum Diskon               38 non-null     object
 5   Harga Fiksasi Setelah ada Diskon/Tidak  38 non-null     object
 6   Angka Rating                            38 non-null     float64
 7   Total Review Fix                        38 non-null     float64
dtypes: float64(2), object(6)
memory usage: 2.5+ KB

Pada kolom **'Jumlah Review'** masih terlihat object tipe datanya karena terdapat kata **'Review'**, Nah dengan membuat fungsi:
- `(rb)?`: Menangkap opsional kata "rb" setelah angka (jika ada). Selain itu, `([\d.]+)`: Menangkap angka (\d) dan tanda desimal (.). Kemudian, `re.match()` digunakan untuk mencocokkan pola dengan string/object.
- Kemudian, melakukan kondisional case dimana
  `if match:
        number = float(match.group(1))          # untuk angka float
        if match.group(2) == 'rb':             # Jika ada 'rb', kalikan 1000
            number *= 1000
        return number
    return None  # Jika tidak cocok, kembalikan None`
  artinya mengubah tipenya menjadi **float** dan melakukan pencarian ketika ada imbuhan 'rb' maka akan dikali 1000 supaya menjadi suatu angka.

Sehingga, pada kolom **'Total Review'** akan menampilkan output angka dari hasil fungsi **extract_review** dimana angka jumlah review pada penginapan tersebut.

### 3. a) Pada Kolom 'Harga Asli Sebelum Diskon' ingin mengubah yang Kosong menjadi Harga Fiksasi setelah ada Diskon

In [ ]:
print(df_tiketcom['Harga Asli Sebelum Diskon'].unique())

['' 'IDR 1.137.272' 'IDR 699.637' 'IDR 4.535.536' 'IDR 1.637.405'
 'IDR 1.427.726' 'IDR 273.222' 'IDR 2.950.413' 'IDR 2.024.256'
 'IDR 1.907.228' 'IDR 3.557.062' 'IDR 3.347.816' 'IDR 3.567.320'
 'IDR 1.983.856' 'IDR 1.935.345' 'IDR 3.034.068' 'IDR 1.930.879'
 'IDR 7.204.364' 'IDR 1.877.685' 'IDR 981.598' 'IDR 2.231.404'
 'IDR 5.312.245' 'IDR 816.243']

Fungsinya untuk melihat value yang unik apa dan juga tipe kosongnya ini null, none atau ''. Ternyata bentuknya '' (object).

In [ ]:
def mengisi_angka (row):
    if row['Harga Asli Sebelum Diskon'] == '':  # Jika kosong
        return row['Harga Fiksasi Setelah ada Diskon/Tidak']  # Gunakan Harga Fiksasi
    return row['Harga Asli Sebelum Diskon']  # Tetap gunakan nilai asli jika ada

# Terapkan fungsi ke kolom
df_tiketcom['Harga Asli Sebelum Diskon'] = df_tiketcom.apply(mengisi_angka, axis=1)
df_tiketcom.head(100)

,Nama Hotel/Villa,Alamat,Rating,Jumlah Review,Harga Asli Sebelum Diskon,Harga Fiksasi Setelah ada Diskon/Tidak,Angka Rating,Total Review Fix
0,Golden Tulip Essential Tangerang,"Tangerang, Tangerang","4,3/5",1.5rb Review,IDR 379.202,IDR 379.202,4.3,1500.0
1,Novotel Tangerang,"Tangerang, Tangerang","4,5/5",681 Review,IDR 904.959,IDR 904.959,4.5,681.0
2,"VIVERE Hotel, ARTOTEL Curated","Medang, Tangerang","4,7/5",464 Review,IDR 789.302,IDR 789.302,4.7,464.0
3,Episode Gading Serpong,"Gading Serpong, Tangerang","4,7/5",1.7rb Review,IDR 1.137.272,IDR 1.136.446,4.7,1700.0
4,Atria Hotel Gading Serpong,"Curug, Tangerang","4,4/5",1.6rb Review,IDR 774.518,IDR 774.518,4.4,1600.0
5,Padina Soho and Residence,"Batuceper, Tangerang","4,5/5",318 Review,IDR 699.637,IDR 360.312,4.5,318.0
6,Potato Head Suites & Studios,"Seminyak, Badung","4,8/5",498 Review,IDR 4.535.536,IDR 4.041.163,4.8,498.0
7,The Capital Hotel and Resort Seminyak,"Seminyak, Badung","4,3/5",727 Review,IDR 709.091,IDR 709.091,4.3,727.0
8,Svarna Suite Seminyak,"Seminyak, Badung","4,3/5",40 Review,IDR 388.435,IDR 388.435,4.3,40.0
9,Lloyds Inn Bali,"Seminyak, Badung","4,4/5",828 Review,IDR 1.637.405,IDR 925.076,4.4,828.0
10,Horison Seminyak Bali,"Kuta, Badung","4,4/5",1.2rb Review,IDR 541.478,IDR 541.478,4.4,1200.0
11,FuramaXclusive Ocean Beach Seminyak,"Seminyak, Badung","4,1/5",687 Review,IDR 952.217,IDR 952.217,4.1,687.0
12,Ramada Encore by Wyndham Bali Seminyak,"Seminyak, Badung","4,5/5",2.2rb Review,IDR 1.427.726,IDR 821.255,4.5,2200.0
13,Primera Hotel Seminyak,"Seminyak, Badung","4,2/5",3.2rb Review,IDR 273.222,IDR 267.758,4.2,3200.0
14,Nikhila Seminyak Bali,"Seminyak, Badung","4,3/5",2.1rb Review,IDR 349.122,IDR 349.122,4.3,2100.0
15,Hotel Indigo BALI SEMINYAK BEACH,"Seminyak, Badung","4,7/5",477 Review,IDR 3.429.540,IDR 3.429.540,4.7,477.0
16,The Salila Beach Resort Seminyak Bali,"Seminyak, Badung","4,7/5",93 Review,IDR 2.950.413,IDR 824.794,4.7,93.0
17,Seminyak Square Hotel And Villas,"Seminyak, Badung","4,3/5",144 Review,IDR 597.763,IDR 597.763,4.3,144.0
18,Mutiara Bali Boutique Resort Villas and Spa,"Seminyak, Badung","4,4/5",150 Review,IDR 2.024.256,IDR 901.879,4.4,150.0
19,Hotel Royal Singapore,"Novena, Singapore","4,2/5",582 Review,IDR 1.379.393,IDR 1.379.393,4.2,582.0
20,Summer View Hotel,"Rochor, Singapore","4,3/5",235 Review,IDR 1.907.228,IDR 1.495.464,4.3,235.0
21,Amrise Hotel Kitchener,"Kallang, Singapore",4/5,58 Review,IDR 1.196.068,IDR 1.196.068,4.0,58.0
22,Oasia Hotel Downtown,"Outram, Singapore","4,7/5",38 Review,IDR 3.557.062,IDR 2.774.806,4.7,38.0
23,Village Hotel Sentosa by Far East Hospitality,"Sentosa Island, Singapore","4,4/5",138 Review,IDR 3.347.816,IDR 2.611.582,4.4,138.0
24,Concorde Hotel Singapore,"Orchard, Singapore","4,4/5",422 Review,IDR 3.567.320,IDR 2.100.190,4.4,422.0
25,Dash Living Rochor,"Rochor, Singapore",4/5,47 Review,IDR 1.983.856,IDR 1.091.559,4.0,47.0
26,Village Hotel Changi by Far East Hospitality,"Changi, Singapore",4/5,152 Review,IDR 1.935.345,IDR 1.622.483,4.0,152.0
27,Aqueen Prestige Hotel Jalan Besar,"Kallang, Singapore","4,6/5",71 Review,IDR 1.513.664,IDR 1.513.664,4.6,71.0
28,Oasia Hotel Novena,"Novena, Singapore","4,7/5",128 Review,IDR 2.133.089,IDR 2.133.089,4.7,128.0
29,Hotel Grand Central,"Orchard, Singapore","4,3/5",1.1rb Review,IDR 1.525.802,IDR 1.525.802,4.3,1100.0
30,Oasia Resort Sentosa by Far East Hospitality,"Sentosa Island, Singapore","4,8/5",6 Review,IDR 3.034.068,IDR 2.543.492,4.8,6.0
31,Hotel JJH Aliwal,"Rochor, Singapore","3,8/5",281 Review,IDR 711.121,IDR 711.121,3.8,281.0
32,Changi Cove Singapore,"Changi, Singapore","4,3/5",184 Review,IDR 1.481.452,IDR 1.481.452,4.3,184.0
33,M Social Singapore,"Singapore River, Singapore",4/5,154 Review,IDR 1.930.879,IDR 1.834.336,4.0,154.0
34,The Daha Luxury Villas,Bali,"4,7/5",58 Review,IDR 7.204.364,IDR 2.808.000,4.7,58.0
35,Awila Villas Kuta,Bali,"4,2/5",96 Review,IDR 1.877.685,IDR 1.600.000,4.2,96.0
36,"Bobocabin Kintamani, Bali",Bali,"4,3/5",528 Review,IDR 981.598,IDR 972.674,4.3,528.0
37,Radea Villa Umalas,Bali,"4,3/5",294 Review,IDR 2.231.404,IDR 725.371,4.3,294.0
38,Lumbini Luxury Villas and Spa,Bali,"4,4/5",170 Review,IDR 5.312.245,IDR 2.275.854,4.4,170.0
39,Daun Bali Seminyak Hotel,"Seminyak, Badung","4,5/5",1.5rb Review,IDR 499.227,IDR 499.227,4.5,1500.0
40,Ramada Encore by Wyndham Bali Seminyak,"Seminyak, Badung","4,5/5",2.2rb Review,IDR 476.405,IDR 476.405,4.5,2200.0
41,Sanur Resort Watujimbar,"Sanur, Denpasar","4,9/5",268 Review,IDR 883.795,IDR 883.795,4.9,268.0
42,Grand Whiz Hotel Nusa Dua,"Nusa Dua, Badung","4,5/5",836 Review,IDR 816.243,IDR 588.283,4.5,836.0
43,Aksari Luxury Resort & Spa Ubud by Ini Vie Hospitality,"Tegallalang, Gianyar","4,6/5",638 Review,IDR 2.561.275,IDR 2.561.275,4.6,638.0

Fungsi `if row['Harga Asli Sebelum Diskon'] == '':  # Jika kosong
        return row['Harga Fiksasi Setelah ada Diskon/Tidak']  # Gunakan Harga Fiksasi
    return row['Harga Asli Sebelum Diskon']  # Tetap gunakan nilai asli jika ada` menunjukkan bahwa mengisi nilai yang kosong jika harga pada **Harga Asli Sebelum Diskon** itu sama dengan harga **Harga Fiksasi Setelah ada Diskon/Tidak** maka nilainya yang diisi adalah dari harga **Harga Fiksasi Setelah ada Diskon/Tidak**. Sedangkan, jika berbeda kondisinya, maka valuenya itu sendiri. Sehingga, data pada kolom yang kosong di **Harga Asli Sebelum Diskon** sudah terisi.

### 3. b) Mengambil nilai/angkanya saja pada Harga sebelum diskon dan Harga fiksasi untuk menjadi tipe data numerik.

In [ ]:
#fungsi
def clean_harga (teks):
    if teks:
        return int(teks.replace('IDR', '').replace('.', '').strip())
    return None
df_tiketcom['Harga Asli Fix'] = df_tiketcom['Harga Asli Sebelum Diskon'].apply(clean_harga)
df_tiketcom['Harga Sesudah Fix'] = df_tiketcom['Harga Fiksasi Setelah ada Diskon/Tidak'].apply(clean_harga)
df_tiketcom.head(100)

,Nama Hotel/Villa,Alamat,Rating,Jumlah Review,Harga Asli Sebelum Diskon,Harga Fiksasi Setelah ada Diskon/Tidak,Angka Rating,Total Review Fix,Harga Asli Fix,Harga Sesudah Fix
0,Golden Tulip Essential Tangerang,"Tangerang, Tangerang","4,3/5",1.5rb Review,IDR 379.202,IDR 379.202,4.3,1500.0,379202,379202
1,Novotel Tangerang,"Tangerang, Tangerang","4,5/5",681 Review,IDR 904.959,IDR 904.959,4.5,681.0,904959,904959
2,"VIVERE Hotel, ARTOTEL Curated","Medang, Tangerang","4,7/5",464 Review,IDR 789.302,IDR 789.302,4.7,464.0,789302,789302
3,Episode Gading Serpong,"Gading Serpong, Tangerang","4,7/5",1.7rb Review,IDR 1.137.272,IDR 1.136.446,4.7,1700.0,1137272,1136446
4,Atria Hotel Gading Serpong,"Curug, Tangerang","4,4/5",1.6rb Review,IDR 774.518,IDR 774.518,4.4,1600.0,774518,774518
5,Padina Soho and Residence,"Batuceper, Tangerang","4,5/5",318 Review,IDR 699.637,IDR 360.312,4.5,318.0,699637,360312
6,Potato Head Suites & Studios,"Seminyak, Badung","4,8/5",498 Review,IDR 4.535.536,IDR 4.041.163,4.8,498.0,4535536,4041163
7,The Capital Hotel and Resort Seminyak,"Seminyak, Badung","4,3/5",727 Review,IDR 709.091,IDR 709.091,4.3,727.0,709091,709091
8,Svarna Suite Seminyak,"Seminyak, Badung","4,3/5",40 Review,IDR 388.435,IDR 388.435,4.3,40.0,388435,388435
9,Lloyds Inn Bali,"Seminyak, Badung","4,4/5",828 Review,IDR 1.637.405,IDR 925.076,4.4,828.0,1637405,925076
10,Horison Seminyak Bali,"Kuta, Badung","4,4/5",1.2rb Review,IDR 541.478,IDR 541.478,4.4,1200.0,541478,541478
11,FuramaXclusive Ocean Beach Seminyak,"Seminyak, Badung","4,1/5",687 Review,IDR 952.217,IDR 952.217,4.1,687.0,952217,952217
12,Ramada Encore by Wyndham Bali Seminyak,"Seminyak, Badung","4,5/5",2.2rb Review,IDR 1.427.726,IDR 821.255,4.5,2200.0,1427726,821255
13,Primera Hotel Seminyak,"Seminyak, Badung","4,2/5",3.2rb Review,IDR 273.222,IDR 267.758,4.2,3200.0,273222,267758
14,Nikhila Seminyak Bali,"Seminyak, Badung","4,3/5",2.1rb Review,IDR 349.122,IDR 349.122,4.3,2100.0,349122,349122
15,Hotel Indigo BALI SEMINYAK BEACH,"Seminyak, Badung","4,7/5",477 Review,IDR 3.429.540,IDR 3.429.540,4.7,477.0,3429540,3429540
16,The Salila Beach Resort Seminyak Bali,"Seminyak, Badung","4,7/5",93 Review,IDR 2.950.413,IDR 824.794,4.7,93.0,2950413,824794
17,Seminyak Square Hotel And Villas,"Seminyak, Badung","4,3/5",144 Review,IDR 597.763,IDR 597.763,4.3,144.0,597763,597763
18,Mutiara Bali Boutique Resort Villas and Spa,"Seminyak, Badung","4,4/5",150 Review,IDR 2.024.256,IDR 901.879,4.4,150.0,2024256,901879
19,Hotel Royal Singapore,"Novena, Singapore","4,2/5",582 Review,IDR 1.379.393,IDR 1.379.393,4.2,582.0,1379393,1379393
20,Summer View Hotel,"Rochor, Singapore","4,3/5",235 Review,IDR 1.907.228,IDR 1.495.464,4.3,235.0,1907228,1495464
21,Amrise Hotel Kitchener,"Kallang, Singapore",4/5,58 Review,IDR 1.196.068,IDR 1.196.068,4.0,58.0,1196068,1196068
22,Oasia Hotel Downtown,"Outram, Singapore","4,7/5",38 Review,IDR 3.557.062,IDR 2.774.806,4.7,38.0,3557062,2774806
23,Village Hotel Sentosa by Far East Hospitality,"Sentosa Island, Singapore","4,4/5",138 Review,IDR 3.347.816,IDR 2.611.582,4.4,138.0,3347816,2611582
24,Concorde Hotel Singapore,"Orchard, Singapore","4,4/5",422 Review,IDR 3.567.320,IDR 2.100.190,4.4,422.0,3567320,2100190
25,Dash Living Rochor,"Rochor, Singapore",4/5,47 Review,IDR 1.983.856,IDR 1.091.559,4.0,47.0,1983856,1091559
26,Village Hotel Changi by Far East Hospitality,"Changi, Singapore",4/5,152 Review,IDR 1.935.345,IDR 1.622.483,4.0,152.0,1935345,1622483
27,Aqueen Prestige Hotel Jalan Besar,"Kallang, Singapore","4,6/5",71 Review,IDR 1.513.664,IDR 1.513.664,4.6,71.0,1513664,1513664
28,Oasia Hotel Novena,"Novena, Singapore","4,7/5",128 Review,IDR 2.133.089,IDR 2.133.089,4.7,128.0,2133089,2133089
29,Hotel Grand Central,"Orchard, Singapore","4,3/5",1.1rb Review,IDR 1.525.802,IDR 1.525.802,4.3,1100.0,1525802,1525802
30,Oasia Resort Sentosa by Far East Hospitality,"Sentosa Island, Singapore","4,8/5",6 Review,IDR 3.034.068,IDR 2.543.492,4.8,6.0,3034068,2543492
31,Hotel JJH Aliwal,"Rochor, Singapore","3,8/5",281 Review,IDR 711.121,IDR 711.121,3.8,281.0,711121,711121
32,Changi Cove Singapore,"Changi, Singapore","4,3/5",184 Review,IDR 1.481.452,IDR 1.481.452,4.3,184.0,1481452,1481452
33,M Social Singapore,"Singapore River, Singapore",4/5,154 Review,IDR 1.930.879,IDR 1.834.336,4.0,154.0,1930879,1834336
34,The Daha Luxury Villas,Bali,"4,7/5",58 Review,IDR 7.204.364,IDR 2.808.000,4.7,58.0,7204364,2808000
35,Awila Villas Kuta,Bali,"4,2/5",96 Review,IDR 1.877.685,IDR 1.600.000,4.2,96.0,1877685,1600000
36,"Bobocabin Kintamani, Bali",Bali,"4,3/5",528 Review,IDR 981.598,IDR 972.674,4.3,528.0,981598,972674
37,Radea Villa Umalas,Bali,"4,3/5",294 Review,IDR 2.231.404,IDR 725.371,4.3,294.0,2231404,725371
38,Lumbini Luxury Villas and Spa,Bali,"4,4/5",170 Review,IDR 5.312.245,IDR 2.275.854,4.4,170.0,5312245,2275854
39,Daun Bali Seminyak Hotel,"Seminyak, Badung","4,5/5",1.5rb Review,IDR 499.227,IDR 499.227,4.5,1500.0,499227,499227
40,Ramada Encore by Wyndham Bali Seminyak,"Seminyak, Badung","4,5/5",2.2rb Review,IDR 476.405,IDR 476.405,4.5,2200.0,476405,476405
41,Sanur Resort Watujimbar,"Sanur, Denpasar","4,9/5",268 Review,IDR 883.795,IDR 883.795,4.9,268.0,883795,883795
42,Grand Whiz Hotel Nusa Dua,"Nusa Dua, Badung","4,5/5",836 Review,IDR 816.243,IDR 588.283,4.5,836.0,816243,588283
43,Aksari Luxury Resort & Spa Ubud by Ini Vie Hospitality,"Tegallalang, Gianyar","4,6/5",638 Review,IDR 2.561.275,IDR 2.561.275,4.6,638.0,2561275,2561275

Fungsi `int(teks.replace('IDR', '').replace('.', '').strip())` digunakan untuk menghapus kata IDR kemudian menghilangkan tanda titik (.) menggunakan fungsi replace(). Kemudian, setelah dihilangkan, akan mengambil **angka numeriknya dan dijadikan tipe integer**. Sehingga, kolom baru yaitu 'Harga Asli Fix' dan 'Harga Sesudah Fix' sudah menjadi nilai harga yang sifatnya integer.

### 3. c) Membuat kategori jika harga tersebut Diskon atau Tidak Diskon dan membuat kolom 'Diskon' yang isinya berapa persentasenya

In [ ]:
#fungsi
def kategori (teks):
    if teks['Harga Asli Fix'] == teks ['Harga Sesudah Fix']:
        return 'Harga Tidak Diskon'
    else:
        return 'Harga Diskon'
df_tiketcom['Kategori Harga'] = df_tiketcom.apply(kategori, axis = 1)

def persentase (teks):
    if teks['Harga Asli Fix'] == teks ['Harga Sesudah Fix']:
        return 0
    else:
       return round(((teks['Harga Asli Fix'] - teks['Harga Sesudah Fix'])/(teks['Harga Asli Fix'])*100), 2)

df_tiketcom['Diskon (%)'] = df_tiketcom.apply(persentase, axis = 1)
df_tiketcom.head(100)

,Nama Hotel/Villa,Alamat,Rating,Jumlah Review,Harga Asli Sebelum Diskon,Harga Fiksasi Setelah ada Diskon/Tidak,Angka Rating,Total Review Fix,Harga Asli Fix,Harga Sesudah Fix,Kategori Harga,Diskon (%)
0,Golden Tulip Essential Tangerang,"Tangerang, Tangerang","4,3/5",1.5rb Review,IDR 379.202,IDR 379.202,4.3,1500.0,379202,379202,Harga Tidak Diskon,0.00
1,Novotel Tangerang,"Tangerang, Tangerang","4,5/5",681 Review,IDR 904.959,IDR 904.959,4.5,681.0,904959,904959,Harga Tidak Diskon,0.00
2,"VIVERE Hotel, ARTOTEL Curated","Medang, Tangerang","4,7/5",464 Review,IDR 789.302,IDR 789.302,4.7,464.0,789302,789302,Harga Tidak Diskon,0.00
3,Episode Gading Serpong,"Gading Serpong, Tangerang","4,7/5",1.7rb Review,IDR 1.137.272,IDR 1.136.446,4.7,1700.0,1137272,1136446,Harga Diskon,0.07
4,Atria Hotel Gading Serpong,"Curug, Tangerang","4,4/5",1.6rb Review,IDR 774.518,IDR 774.518,4.4,1600.0,774518,774518,Harga Tidak Diskon,0.00
5,Padina Soho and Residence,"Batuceper, Tangerang","4,5/5",318 Review,IDR 699.637,IDR 360.312,4.5,318.0,699637,360312,Harga Diskon,48.50
6,Potato Head Suites & Studios,"Seminyak, Badung","4,8/5",498 Review,IDR 4.535.536,IDR 4.041.163,4.8,498.0,4535536,4041163,Harga Diskon,10.90
7,The Capital Hotel and Resort Seminyak,"Seminyak, Badung","4,3/5",727 Review,IDR 709.091,IDR 709.091,4.3,727.0,709091,709091,Harga Tidak Diskon,0.00
8,Svarna Suite Seminyak,"Seminyak, Badung","4,3/5",40 Review,IDR 388.435,IDR 388.435,4.3,40.0,388435,388435,Harga Tidak Diskon,0.00
9,Lloyds Inn Bali,"Seminyak, Badung","4,4/5",828 Review,IDR 1.637.405,IDR 925.076,4.4,828.0,1637405,925076,Harga Diskon,43.50
10,Horison Seminyak Bali,"Kuta, Badung","4,4/5",1.2rb Review,IDR 541.478,IDR 541.478,4.4,1200.0,541478,541478,Harga Tidak Diskon,0.00
11,FuramaXclusive Ocean Beach Seminyak,"Seminyak, Badung","4,1/5",687 Review,IDR 952.217,IDR 952.217,4.1,687.0,952217,952217,Harga Tidak Diskon,0.00
12,Ramada Encore by Wyndham Bali Seminyak,"Seminyak, Badung","4,5/5",2.2rb Review,IDR 1.427.726,IDR 821.255,4.5,2200.0,1427726,821255,Harga Diskon,42.48
13,Primera Hotel Seminyak,"Seminyak, Badung","4,2/5",3.2rb Review,IDR 273.222,IDR 267.758,4.2,3200.0,273222,267758,Harga Diskon,2.00
14,Nikhila Seminyak Bali,"Seminyak, Badung","4,3/5",2.1rb Review,IDR 349.122,IDR 349.122,4.3,2100.0,349122,349122,Harga Tidak Diskon,0.00
15,Hotel Indigo BALI SEMINYAK BEACH,"Seminyak, Badung","4,7/5",477 Review,IDR 3.429.540,IDR 3.429.540,4.7,477.0,3429540,3429540,Harga Tidak Diskon,0.00
16,The Salila Beach Resort Seminyak Bali,"Seminyak, Badung","4,7/5",93 Review,IDR 2.950.413,IDR 824.794,4.7,93.0,2950413,824794,Harga Diskon,72.04
17,Seminyak Square Hotel And Villas,"Seminyak, Badung","4,3/5",144 Review,IDR 597.763,IDR 597.763,4.3,144.0,597763,597763,Harga Tidak Diskon,0.00
18,Mutiara Bali Boutique Resort Villas and Spa,"Seminyak, Badung","4,4/5",150 Review,IDR 2.024.256,IDR 901.879,4.4,150.0,2024256,901879,Harga Diskon,55.45
19,Hotel Royal Singapore,"Novena, Singapore","4,2/5",582 Review,IDR 1.379.393,IDR 1.379.393,4.2,582.0,1379393,1379393,Harga Tidak Diskon,0.00
20,Summer View Hotel,"Rochor, Singapore","4,3/5",235 Review,IDR 1.907.228,IDR 1.495.464,4.3,235.0,1907228,1495464,Harga Diskon,21.59
21,Amrise Hotel Kitchener,"Kallang, Singapore",4/5,58 Review,IDR 1.196.068,IDR 1.196.068,4.0,58.0,1196068,1196068,Harga Tidak Diskon,0.00
22,Oasia Hotel Downtown,"Outram, Singapore","4,7/5",38 Review,IDR 3.557.062,IDR 2.774.806,4.7,38.0,3557062,2774806,Harga Diskon,21.99
23,Village Hotel Sentosa by Far East Hospitality,"Sentosa Island, Singapore","4,4/5",138 Review,IDR 3.347.816,IDR 2.611.582,4.4,138.0,3347816,2611582,Harga Diskon,21.99
24,Concorde Hotel Singapore,"Orchard, Singapore","4,4/5",422 Review,IDR 3.567.320,IDR 2.100.190,4.4,422.0,3567320,2100190,Harga Diskon,41.13
25,Dash Living Rochor,"Rochor, Singapore",4/5,47 Review,IDR 1.983.856,IDR 1.091.559,4.0,47.0,1983856,1091559,Harga Diskon,44.98
26,Village Hotel Changi by Far East Hospitality,"Changi, Singapore",4/5,152 Review,IDR 1.935.345,IDR 1.622.483,4.0,152.0,1935345,1622483,Harga Diskon,16.17
27,Aqueen Prestige Hotel Jalan Besar,"Kallang, Singapore","4,6/5",71 Review,IDR 1.513.664,IDR 1.513.664,4.6,71.0,1513664,1513664,Harga Tidak Diskon,0.00
28,Oasia Hotel Novena,"Novena, Singapore","4,7/5",128 Review,IDR 2.133.089,IDR 2.133.089,4.7,128.0,2133089,2133089,Harga Tidak Diskon,0.00
29,Hotel Grand Central,"Orchard, Singapore","4,3/5",1.1rb Review,IDR 1.525.802,IDR 1.525.802,4.3,1100.0,1525802,1525802,Harga Tidak Diskon,0.00
30,Oasia Resort Sentosa by Far East Hospitality,"Sentosa Island, Singapore","4,8/5",6 Review,IDR 3.034.068,IDR 2.543.492,4.8,6.0,3034068,2543492,Harga Diskon,16.17
31,Hotel JJH Aliwal,"Rochor, Singapore","3,8/5",281 Review,IDR 711.121,IDR 711.121,3.8,281.0,711121,711121,Harga Tidak Diskon,0.00
32,Changi Cove Singapore,"Changi, Singapore","4,3/5",184 Review,IDR 1.481.452,IDR 1.481.452,4.3,184.0,1481452,1481452,Harga Tidak Diskon,0.00
33,M Social Singapore,"Singapore River, Singapore",4/5,154 Review,IDR 1.930.879,IDR 1.834.336,4.0,154.0,1930879,1834336,Harga Diskon,5.00
34,The Daha Luxury Villas,Bali,"4,7/5",58 Review,IDR 7.204.364,IDR 2.808.000,4.7,58.0,7204364,2808000,Harga Diskon,61.02
35,Awila Villas Kuta,Bali,"4,2/5",96 Review,IDR 1.877.685,IDR 1.600.000,4.2,96.0,1877685,1600000,Harga Diskon,14.79
36,"Bobocabin Kintamani, Bali",Bali,"4,3/5",528 Review,IDR 981.598,IDR 972.674,4.3,528.0,981598,972674,Harga Diskon,0.91
37,Radea Villa Umalas,Bali,"4,3/5",294 Review,IDR 2.231.404,IDR 725.371,4.3,294.0,2231404,725371,Harga Diskon,67.49
38,Lumbini Luxury Villas and Spa,Bali,"4,4/5",170 Review,IDR 5.312.245,IDR 2.275.854,4.4,170.0,5312245,2275854,Harga Diskon,57.16
39,Daun Bali Seminyak Hotel,"Seminyak, Badung","4,5/5",1.5rb Review,IDR 499.227,IDR 499.227,4.5,1500.0,499227,499227,Harga Tidak Diskon,0.00
40,Ramada Encore by Wyndham Bali Seminyak,"Seminyak, Badung","4,5/5",2.2rb Review,IDR 476.405,IDR 476.405,4.5,2200.0,476405,476405,Harga Tidak Diskon,0.00
41,Sanur Resort Watujimbar,"Sanur, Denpasar","4,9/5",268 Review,IDR 883.795,IDR 883.795,4.9,268.0,883795,883795,Harga Tidak Diskon,0.00
42,Grand Whiz Hotel Nusa Dua,"Nusa Dua, Badung","4,5/5",836 Review,IDR 816.243,IDR 588.283,4.5,836.0,816243,588283,Harga Diskon,27.93
43,Aksari Luxury Resort & Spa Ubud by Ini Vie Hospitality,"Tegallalang, Gianyar","4,6/5",638 Review,IDR 2.561.275,IDR 2.561.275,4.6,638.0,2561275,2561275,Harga Tidak Diskon,0.00

- Pada fungsi Pertama 'kategori' digunakan untuk membuat kategori berdasarkan kolom **'Harga Asli Fix'** dan **'Harga Sesudah Fix'** dimana jika harga asli dengan harga sesudah itu nilainya sama maka kategorinya **Harga Tidak Diskon**, begitu sebaliknya jika berbeda maka kategorinya **Harga Diskon**.
- Pada fungi Kedua 'persentase' digunakan untuk menghitung persentase diskon yang didapatkan berdasarkan kolom **'Harga Asli Fix'** dan **'Harga Sesudah Fix'** dengan rumus `((Harga Asli - Harga Sesudah( /( Harga Asli)) * 100` dan dilakukan pembulatan menggunakan `round()` sebanyak 2 digit belakang koma.

Sehingga, hasilnya sudah dilakukan pada kolom baru **'Kategori Harga' dan 'Diskon %'**

# Penyimpanan Dataframe menjadi csv

In [ ]:
df_tiketcom.columns

Index(['Nama Hotel/Villa', 'Alamat', 'Rating', 'Jumlah Review',
       'Harga Asli Sebelum Diskon', 'Harga Fiksasi Setelah ada Diskon/Tidak',
       'Angka Rating', 'Total Review Fix', 'Harga Asli Fix',
       'Harga Sesudah Fix', 'Kategori Harga', 'Diskon (%)'],
      dtype='object')

In [ ]:
tiketcom_bersih_data = df_tiketcom[['Nama Hotel/Villa', 'Alamat', 'Angka Rating', 'Total Review Fix','Harga Asli Fix',
       'Harga Sesudah Fix', 'Kategori Harga', 'Diskon (%)']]
tiketcom_bersih_data.head(100)

,Nama Hotel/Villa,Alamat,Angka Rating,Total Review Fix,Harga Asli Fix,Harga Sesudah Fix,Kategori Harga,Diskon (%)
0,Golden Tulip Essential Tangerang,"Tangerang, Tangerang",4.3,1500.0,379202,379202,Harga Tidak Diskon,0.00
1,Novotel Tangerang,"Tangerang, Tangerang",4.5,681.0,904959,904959,Harga Tidak Diskon,0.00
2,"VIVERE Hotel, ARTOTEL Curated","Medang, Tangerang",4.7,464.0,789302,789302,Harga Tidak Diskon,0.00
3,Episode Gading Serpong,"Gading Serpong, Tangerang",4.7,1700.0,1137272,1136446,Harga Diskon,0.07
4,Atria Hotel Gading Serpong,"Curug, Tangerang",4.4,1600.0,774518,774518,Harga Tidak Diskon,0.00
5,Padina Soho and Residence,"Batuceper, Tangerang",4.5,318.0,699637,360312,Harga Diskon,48.50
6,Potato Head Suites & Studios,"Seminyak, Badung",4.8,498.0,4535536,4041163,Harga Diskon,10.90
7,The Capital Hotel and Resort Seminyak,"Seminyak, Badung",4.3,727.0,709091,709091,Harga Tidak Diskon,0.00
8,Svarna Suite Seminyak,"Seminyak, Badung",4.3,40.0,388435,388435,Harga Tidak Diskon,0.00
9,Lloyds Inn Bali,"Seminyak, Badung",4.4,828.0,1637405,925076,Harga Diskon,43.50
10,Horison Seminyak Bali,"Kuta, Badung",4.4,1200.0,541478,541478,Harga Tidak Diskon,0.00
11,FuramaXclusive Ocean Beach Seminyak,"Seminyak, Badung",4.1,687.0,952217,952217,Harga Tidak Diskon,0.00
12,Ramada Encore by Wyndham Bali Seminyak,"Seminyak, Badung",4.5,2200.0,1427726,821255,Harga Diskon,42.48
13,Primera Hotel Seminyak,"Seminyak, Badung",4.2,3200.0,273222,267758,Harga Diskon,2.00
14,Nikhila Seminyak Bali,"Seminyak, Badung",4.3,2100.0,349122,349122,Harga Tidak Diskon,0.00
15,Hotel Indigo BALI SEMINYAK BEACH,"Seminyak, Badung",4.7,477.0,3429540,3429540,Harga Tidak Diskon,0.00
16,The Salila Beach Resort Seminyak Bali,"Seminyak, Badung",4.7,93.0,2950413,824794,Harga Diskon,72.04
17,Seminyak Square Hotel And Villas,"Seminyak, Badung",4.3,144.0,597763,597763,Harga Tidak Diskon,0.00
18,Mutiara Bali Boutique Resort Villas and Spa,"Seminyak, Badung",4.4,150.0,2024256,901879,Harga Diskon,55.45
19,Hotel Royal Singapore,"Novena, Singapore",4.2,582.0,1379393,1379393,Harga Tidak Diskon,0.00
20,Summer View Hotel,"Rochor, Singapore",4.3,235.0,1907228,1495464,Harga Diskon,21.59
21,Amrise Hotel Kitchener,"Kallang, Singapore",4.0,58.0,1196068,1196068,Harga Tidak Diskon,0.00
22,Oasia Hotel Downtown,"Outram, Singapore",4.7,38.0,3557062,2774806,Harga Diskon,21.99
23,Village Hotel Sentosa by Far East Hospitality,"Sentosa Island, Singapore",4.4,138.0,3347816,2611582,Harga Diskon,21.99
24,Concorde Hotel Singapore,"Orchard, Singapore",4.4,422.0,3567320,2100190,Harga Diskon,41.13
25,Dash Living Rochor,"Rochor, Singapore",4.0,47.0,1983856,1091559,Harga Diskon,44.98
26,Village Hotel Changi by Far East Hospitality,"Changi, Singapore",4.0,152.0,1935345,1622483,Harga Diskon,16.17
27,Aqueen Prestige Hotel Jalan Besar,"Kallang, Singapore",4.6,71.0,1513664,1513664,Harga Tidak Diskon,0.00
28,Oasia Hotel Novena,"Novena, Singapore",4.7,128.0,2133089,2133089,Harga Tidak Diskon,0.00
29,Hotel Grand Central,"Orchard, Singapore",4.3,1100.0,1525802,1525802,Harga Tidak Diskon,0.00
30,Oasia Resort Sentosa by Far East Hospitality,"Sentosa Island, Singapore",4.8,6.0,3034068,2543492,Harga Diskon,16.17
31,Hotel JJH Aliwal,"Rochor, Singapore",3.8,281.0,711121,711121,Harga Tidak Diskon,0.00
32,Changi Cove Singapore,"Changi, Singapore",4.3,184.0,1481452,1481452,Harga Tidak Diskon,0.00
33,M Social Singapore,"Singapore River, Singapore",4.0,154.0,1930879,1834336,Harga Diskon,5.00
34,The Daha Luxury Villas,Bali,4.7,58.0,7204364,2808000,Harga Diskon,61.02
35,Awila Villas Kuta,Bali,4.2,96.0,1877685,1600000,Harga Diskon,14.79
36,"Bobocabin Kintamani, Bali",Bali,4.3,528.0,981598,972674,Harga Diskon,0.91
37,Radea Villa Umalas,Bali,4.3,294.0,2231404,725371,Harga Diskon,67.49
38,Lumbini Luxury Villas and Spa,Bali,4.4,170.0,5312245,2275854,Harga Diskon,57.16
39,Daun Bali Seminyak Hotel,"Seminyak, Badung",4.5,1500.0,499227,499227,Harga Tidak Diskon,0.00
40,Ramada Encore by Wyndham Bali Seminyak,"Seminyak, Badung",4.5,2200.0,476405,476405,Harga Tidak Diskon,0.00
41,Sanur Resort Watujimbar,"Sanur, Denpasar",4.9,268.0,883795,883795,Harga Tidak Diskon,0.00
42,Grand Whiz Hotel Nusa Dua,"Nusa Dua, Badung",4.5,836.0,816243,588283,Harga Diskon,27.93
43,Aksari Luxury Resort & Spa Ubud by Ini Vie Hospitality,"Tegallalang, Gianyar",4.6,638.0,2561275,2561275,Harga Tidak Diskon,0.00

In [ ]:
# Reset indeks dan buat mulai dari 1
tiketcom_bersih_data_reset = tiketcom_bersih_data.reset_index(drop=True)  # Menghapus indeks lama
tiketcom_bersih_data_reset.index += 1  # Mulai dari 1

tiketcom_bersih_data_reset.to_csv('C:/Users/acer/Downloads/Data Tiketcom Reservasi Hotel.csv', index_label='No')

-- FINISH --